In [15]:
import numpy as np
import pandas as pd

In [16]:
df=pd.read_csv("C:\Customer_data.csv")
print(df)
df.head()

      Ticket ID        Customer Name              Customer Email  \
0             1        Marisa Obrien  carrollallison@example.com
1             2         Jessica Rios    clarkeashley@example.com
2             3  Christopher Robbins   gonzalestracy@example.com
3             4     Christina Dillon    bradleyolson@example.org
4             5    Alexander Carroll     bradleymark@example.com
...         ...                  ...                         ...
8464       8465           David Todd          adam28@example.net
8465       8466           Lori Davis       russell68@example.com
8466       8467      Michelle Kelley        ashley83@example.org
8467       8468     Steven Rodriguez         fpowell@example.org
8468       8469      Steven Davis MD          lori20@example.net

      Customer Age Customer Gender       Product Purchased Date of Purchase  \
0               32           Other              GoPro Hero       2021-03-22
1               42          Female             LG Smart TV       2021-05-22
2               48           Other                Dell XPS       2020-07-14
3               27          Female        Microsoft Office       2020-11-13
4               67          Female        Autodesk AutoCAD       2020-02-04
...            ...             ...                     ...              ...
8464            22          Female                 LG OLED       2021-12-08
8465            27          Female  Bose SoundLink Speaker       2020-02-22
8466            57          Female     GoPro Action Camera       2021-08-17
8467            54            Male             PlayStation       2021-10-16
8468            53           Other      Philips Hue Lights       2020-06-01

          Ticket Type            Ticket Subject  \
0     Technical issue             Product setup
1     Technical issue  Peripheral compatibility
2     Technical issue           Network problem
3     Billing inquiry            Account access
4     Billing inquiry                 Data loss
...               ...                       ...
8464  Product inquiry      Installation support
8465  Technical issue            Refund request
8466  Technical issue            Account access
8467  Product inquiry             Payment issue
8468  Billing inquiry            Hardware issue

                                     Ticket Description  \
0     I'm having an issue with the {product_purchase...
1     I'm having an issue with the {product_purchase...
2     I'm facing a problem with my {product_purchase...
3     I'm having an issue with the {product_purchase...
4     I'm having an issue with the {product_purchase...
...                                                 ...
8464  My {product_purchased} is making strange noise...
8465  I'm having an issue with the {product_purchase...
8466  I'm having an issue with the {product_purchase...
8467  I'm having an issue with the {product_purchase...
8468  There seems to be a hardware problem with my {...

                  Ticket Status  \
0     Pending Customer Response
1     Pending Customer Response
2                        Closed
3                        Closed
4                        Closed
...                         ...
8464                       Open
8465                       Open
8466                     Closed
8467                     Closed
8468                       Open

                                         Resolution Ticket Priority  \
0                                               NaN        Critical
1                                               NaN        Critical
2      Case maybe show recently my computer follow.             Low
3     Try capital clearly never color toward story.             Low
4                       West decision evidence bit.             Low
...                                             ...             ...
8464                                            NaN             Low
8465                                            NaN        Critical
8466          Eight account century nature kitchen.            High
8467                          We seat culture plan.          Medium
8468                                            NaN            High

     Ticket Channel  First Response Time   Time to Resolution  \
0      Social media  2023-06-01 12:15:36                  NaN
1              Chat  2023-06-01 16:45:38                  NaN
2      Social media  2023-06-01 11:14:38  2023-06-01 18:05:38
3      Social media  2023-06-01 07:29:40  2023-06-01 01:57:40
4             Email  2023-06-01 00:12:42  2023-06-01 19:53:42
...             ...                  ...                  ...
8464          Phone                  NaN                  NaN
8465          Email                  NaN                  NaN
8466   Social media  2023-06-01 09:44:22  2023-06-01 04:31:22
8467          Email  2023-06-01 18:28:24  2023-06-01 05:32:24
8468          Phone                  NaN                  NaN

      Customer Satisfaction Rating
0                              NaN
1                              NaN
2                              3.0
3                              3.0
4                              1.0
...                            ...
8464                           NaN
8465                           NaN
8466                           3.0
8467                           3.0
8468                           NaN

[8469 rows x 17 columns]

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\SAVITA YADAV\AppData\Local\Temp\ipykernel_2184\3811328991.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv("C:\Customer_data.csv")

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [18]:
df.info()
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB
Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [20]:
text_column=df.select_dtypes(include=["object","string"]).columns.to_list()
print(text_column)

['Customer Name', 'Customer Email', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution']

In [21]:
cleaned_df=df.copy()

In [24]:
import re

cleaned_df = df.copy()

text_columns = cleaned_df.select_dtypes(
    include="object"
).columns

for col in text_columns:
    cleaned_df[col] = cleaned_df[col].apply(
        lambda x: re.sub(r"\s+", " ", x.strip())
        if isinstance(x, str) else x
    )

print("Text cleaning completed!")

Text cleaning completed!

In [25]:
for col in cleaned_df.columns:
    if "name" in col.lower():
        cleaned_df[col] = cleaned_df[col].str.title()

    elif "email" in col.lower():
        cleaned_df[col] = cleaned_df[col].str.lower()

print("Names and emails cleaned!")

Names and emails cleaned!

In [26]:
print("Before Cleaning:")
display(df.head())

print("After Cleaning:")
display(cleaned_df.head())

Before Cleaning:

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

After Cleaning:

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [27]:
cleaned_df.to_csv("cleaned_customer_data.csv", index=False)

print("Cleaned dataset saved!")

Cleaned dataset saved!

In [28]:
comparison = pd.DataFrame({
    "before": df.select_dtypes(include="object").iloc[:, 0],
    "after": cleaned_df.select_dtypes(include="object").iloc[:, 0]
})

comparison.to_csv("before_after_comparison.csv", index=False)

print("Comparison file saved!")

Comparison file saved!