In [1]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving retail_sales_dataset.csv to retail_sales_dataset.csv

In [4]:
df = pd.read_csv('retail_sales_dataset.csv')

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [5]:
df['Date'].head(10)

0    2023-11-24
1    2023-02-27
2    2023-01-13
3    2023-05-21
4    2023-05-06
5    2023-04-25
6    2023-03-13
7    2023-02-22
8    2023-12-13
9    2023-10-07
Name: Date, dtype: object

In [6]:
print(df['Date'].dtype)

object

In [7]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='%Y-%m-%d',
    errors='coerce'
)

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [8]:
print(df['Date'].dtype)

datetime64[ns]

In [9]:
invalid_dates = df[df['Date'].isna()]

print("Invalid dates:", len(invalid_dates))

invalid_dates

Invalid dates: 0

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

In [10]:
issue_log = df[df['Date'].isna()].copy()

issue_log['Issue'] = 'Invalid date'

issue_log

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, Issue]
Index: []

In [11]:
df['Date'].dt.strftime('%d-%m-%Y').head(10)

0    24-11-2023
1    27-02-2023
2    13-01-2023
3    21-05-2023
4    06-05-2023
5    25-04-2023
6    13-03-2023
7    22-02-2023
8    13-12-2023
9    07-10-2023
Name: Date, dtype: object

In [12]:
print("Total rows:", len(df))
print("Missing dates:", df['Date'].isna().sum())
print("Date datatype:", df['Date'].dtype)

df.head()

Total rows: 1000
Missing dates: 0
Date datatype: datetime64[ns]

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [16]:
df.to_csv('cleaned_retail_sales.csv', index=False)

issue_log.to_csv('date_issue_log.csv', index=False)

print("Both files saved successfully!")

Both files saved successfully!

In [18]:
from google.colab import files

files.download('cleaned_retail_sales.csv')
files.download('date_issue_log.csv')